
theme:
  openapi:
    theme:
      layout:
        showDarkRightPanel: true
      components:
        panels:
          borderRadius: "8px"  # Default value
          backgroundColor: "#212121"  # Set your desired background color here
        httpBadges:
          color: "#212121"
      colors:
        primary:
          contrastText: "#212121"
          main: "#212121"
          dark: "#212121"
          light: "#212121"
        text:
          primary: "#000000"
          secondary: "#000000"
          light: "#212121"
        secondary:
          main: "#FFFFFF"
          light: "#212121"
        http:
          basic: "#212121"
      typography:
        fontFamily: "--apple-system,
          BlinkMacSystemFont,
          'Segoe UI',
          Roboto,
          'Helvetica Neue',
          Arial,
          sans-serif,
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol'"

        fontSize: "16px"
        rightPanelHeading:
          fontFamily: "--apple-system,
            BlinkMacSystemFont,
            'Segoe UI',
            Roboto,
            'Helvetica Neue',
            Arial,
            sans-serif,
            'Apple Color Emoji',
            'Segoe UI Emoji',
            'Segoe UI Symbol'"
          fontWeight: "600"
          color: "#212121"
        heading1:
          fontFamily: "--apple-system,
            BlinkMacSystemFont,
            'Segoe UI',
            Roboto,
            'Helvetica Neue',
            Arial,
            sans-serif,
            'Apple Color Emoji',
            'Segoe UI Emoji',
            'Segoe UI Symbol'"
          fontWeight: "600"
      spacing:
        unit: 5
      sidebar:
        backgroundColor: "#212121"
        textColor: "#FFFFFF"
      rightPanel:
        backgroundColor: "#171717"
        panelBackgroundColor: "#212121"
        panelControlsBackgroundColor: "#212121"
        textColor: "#FFFFFF"
      codeBlock:
        backgroundColor: "#212121"
      schema:
        nestedBackground: "#212121"
        linesColor: "#212121"
        caretColor: "#212121"
        typeNameColor: "#212121"
        typeTitleColor: "#212121"
      fab:
        backgroundColor: "#212121"
        color: "#212121"


